# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kk_wqgkG5ziBHOyl1tys9JxKVzCrxaF0
"""

pepito = 1
maria = 17
casa = 4
conteo = 0
conteo2 = 0

while pepito != maria:
    pepito += 1
    conteo += 1

print("Desde pepito hasta maria hay:", conteo, "casas")
pepito=1

while pepito != casa:
    pepito += 1
    conteo2 += 1

print("Desde pepito hasta la casa hay:", casa, "casas")

pepito_x = 2
pepito_y = 2

maria_x = 4
maria_y = 4

distancia_x = abs(maria_x - pepito_x)
distancia_y = abs(maria_y - pepito_y)

casas = distancia_x + distancia_y

print("Número de casas para llegar:", casas)

# Posición inicial de pepito
pepito_x = 2
pepito_y = 2

# Posición de maria
maria_x = 4
maria_y = 4

# Calcula la distancia en cada eje
distancia_x = abs(maria_x - pepito_x)
distancia_y = abs(maria_y - pepito_y)

# Calcula el número de cuadras o manzanas (casas) para llegar
cuadras_x = distancia_x  # Distancia en el eje x
cuadras_y = distancia_y  # Distancia en el eje y

# Imprime el número de cuadras o manzanas en la ruta
print("Número de cuadras (casas) para llegar:", cuadras_x + cuadras_y)

# Coordenadas de las dos casas
f1=int(input("Ingrese la fila de la primera casa: "))
c1=int(input("Ingrese la columna de la primera casa"))
casa1 = (f1, c1)  # Fila 0, columna 0
f2=int(input("Ingrese la fila de la segunda casa: "))
c2=int(input("Ingrese la columna de la segunda casa"))
casa2 = (f2, c2)  # Fila 2, columna 3
import math
# Calculamos la distancia utilizando la fórmula de distancia euclidiana
distancia = math.sqrt((casa2[0] - casa1[0]) ** 2 + (casa2[1] - casa1[1]) ** 2)
distancia = distancia-1
# Imprimimos el resultado
print("el amor de tu vida esta a:", distancia,"casas de distancia")

# Coordenadas de las dos casas
f1 = int(input("Ingrese la fila de la primera casa: "))
c1 = int(input("Ingrese la columna de la primera casa: "))
f2 = int(input("Ingrese la fila de la segunda casa: "))
c2 = int(input("Ingrese la columna de la segunda casa: "))

# Calculamos la distancia utilizando la fórmula de distancia euclidiana
distancia = ((f2 - f1) ** 2 + (c2 - c1) ** 2) ** 0.5

# Imprimimos el resultado
print("La distancia entre las dos casas es:", distancia)